"""parent and children with F keys

Revision ID: eccce2edb8e4
Revises: 6bdc7228f252
Create Date: 2022-07-22 14:55:11.094115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eccce2edb8e4'
down_revision = '6bdc7228f252'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('child', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'child', 'parent', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'child', type_='foreignkey')
    op.drop_column('child', 'parent_id')
    # ### end Alembic commands ###
