from postgres:14.1-alpine as base

#args and envs , get from env or defult 
ARG POSTGRES_USER=postgres
ENV POSTGRES_USER=POSTGRES_USER

ARG POSTGRES_PASSWORD=postgres
ENV POSTGRES_PASSWORD=POSTGRES_PASSWORD


# COPY mig_db.sh docker-entrypoint-initdb.d/mig_db.sh
COPY init.sql docker-entrypoint-initdb.d/

# RUN [ "pwd" ]
# RUN [ "ls -l" ]
# RUN   ["cat db/mig_db.sh >> docker-entrypoint-initdb.d/mig_db.sh "]
