#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER docker;
	CREATE DATABASE $SANDBOX_DB_SCHEMA';
	GRANT ALL PRIVILEGES ON DATABASE docker TO docker;
    CREATE SCHEMA IF NOT EXISTS $SANDBOX_DB_SCHEMA;
EOSQL

# psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$SANDBOX_DB_SCHEMA" <<-EOSQL
# 	SELECT 'CREATE DATABASE $SANDBOX_DB_SCHEMA'
#     WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '$SANDBOX_DB_SCHEMA')\gexec;
#     CREATE SCHEMA IF NOT EXISTS $SANDBOX_DB_SCHEMA;

# EOSQL
